# Настройки для PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/real-estate-app
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Настройки для Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
logging:
  level:
    org.springframework.web: INFO
    com.example: DEBUG
springdoc:
  api-docs:
    enabled: true # Включение генерации OpenAPI JSON
  swagger-ui:
    enabled: true # Включение Swagger UI
    path: /swagger-ui.html
